version: '3.8'

services:

  service-registry:
    build: ./backend/service-registry
    container_name: service-registry
    ports:
      - "8761:8761"
    networks:
      - quiz-network

  api-gateway:
    build: ./backend/api-gateway
    container_name: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - service-registry
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka
    networks:
      - quiz-network

  quiz-service:
    build: ./backend/quiz_service
    container_name: quiz-service
    ports:
      - "8081:8081"
    depends_on:
      - service-registry
      - quiz-db
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka
    networks:
      - quiz-network

  question-service:
    build: ./backend/question_service
    container_name: question-service
    ports:
      - "8082:8082"
    depends_on:
      - service-registry
      - question-db
    environment:
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://service-registry:8761/eureka
    networks:
      - quiz-network

  quiz-frontend:
    build: ./frontend/quiz_frontend
    container_name: quiz-frontend
    ports:
      - "3000:80"
    depends_on:
      - api-gateway
    networks:
      - quiz-network

  quiz-db:
    image: mysql:8.0
    container_name: quiz-db
    environment:
      MYSQL_ROOT_PASSWORD: root@12345
      MYSQL_DATABASE: microQuizdb
    ports:
      - "3307:3306"
    networks:
      - quiz-network

  question-db:
    image: mysql:8.0
    container_name: question-db
    environment:
      MYSQL_ROOT_PASSWORD: root@12345
      MYSQL_DATABASE: questiondb
    ports:
      - "3308:3306"
    networks:
      - quiz-network

networks:
  quiz-network:
    driver: bridge
